#!/usr/bin/env bash
## Run Puppet locally using puppet apply

set -e

/usr/bin/puppet apply /srv/code/homepass/RaspberryPi/manifests \
  --color=false                                       \
  --verbose                                           \
  --modulepath=/srv/code/homepass/RaspberryPi/modules

## Log status of the Puppet run
if [ $? -eq 0 ]
then
  /usr/bin/logger -i "Puppet has run successfully" -t "puppet-run"
  exit 0
else
  /usr/bin/logger -i "Puppet has ran into an error, please run Puppet manually" -t "puppet-run"
  exit 1
fi
